<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 75,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 76,
                'data_type_id' => 8,
                'field' => 'ci',
                'type' => 'text',
                'display_name' => 'Ci / Pasaporte',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191|unique:people"},"display":{"width":4}}',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 77,
                'data_type_id' => 8,
                'field' => 'first_name',
                'type' => 'text',
                'display_name' => 'Primer Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 5,
            ),
            24 => 
            array (
                'id' => 78,
                'data_type_id' => 8,
                'field' => 'middle_name',
                'type' => 'text',
            'display_name' => 'Segundo Nombre (Opcional)',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 6,
            ),
            25 => 
            array (
                'id' => 79,
                'data_type_id' => 8,
                'field' => 'paternal_surname',
                'type' => 'text',
                'display_name' => 'Apeliido Paterno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 7,
            ),
            26 => 
            array (
                'id' => 80,
                'data_type_id' => 8,
                'field' => 'maternal_surname',
                'type' => 'text',
                'display_name' => 'Apeliido Materno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 8,
            ),
            27 => 
            array (
                'id' => 81,
                'data_type_id' => 8,
                'field' => 'birth_date',
                'type' => 'date',
                'display_name' => 'Fecha de Nacimiento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 3,
            ),
            28 => 
            array (
                'id' => 82,
                'data_type_id' => 8,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email / Correo electronico',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 9,
            ),
            29 => 
            array (
                'id' => 83,
                'data_type_id' => 8,
                'field' => 'phone',
                'type' => 'number',
                'display_name' => 'Telefono / Celular',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":2}}',
                'order' => 11,
            ),
            30 => 
            array (
                'id' => 84,
                'data_type_id' => 8,
                'field' => 'address',
                'type' => 'text_area',
                'display_name' => 'Dirección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":12}}',
                'order' => 13,
            ),
            31 => 
            array (
                'id' => 85,
                'data_type_id' => 8,
                'field' => 'gender',
                'type' => 'select_dropdown',
                'display_name' => 'Género',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"options":{"Masculino":"Masculino","Femenino":"Femenino"},"display":{"width":4},"validation":{"rule":"required"}}',
                'order' => 4,
            ),
            32 => 
            array (
                'id' => 86,
                'data_type_id' => 8,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Fotografía',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":6},"resize":{"width":"1000","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 12,
            ),
            33 => 
            array (
                'id' => 87,
                'data_type_id' => 8,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 14,
            ),
            34 => 
            array (
                'id' => 88,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            35 => 
            array (
                'id' => 89,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            36 => 
            array (
                'id' => 90,
                'data_type_id' => 8,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 17,
            ),
            37 => 
            array (
                'id' => 91,
                'data_type_id' => 8,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            38 => 
            array (
                'id' => 92,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            39 => 
            array (
                'id' => 93,
                'data_type_id' => 8,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 20,
            ),
            40 => 
            array (
                'id' => 94,
                'data_type_id' => 8,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 21,
            ),
            41 => 
            array (
                'id' => 95,
                'data_type_id' => 8,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 22,
            ),
            42 => 
            array (
                'id' => 96,
                'data_type_id' => 1,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verified At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            43 => 
            array (
                'id' => 97,
                'data_type_id' => 1,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            44 => 
            array (
                'id' => 98,
                'data_type_id' => 1,
                'field' => 'person_id',
                'type' => 'text',
                'display_name' => 'Person Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            45 => 
            array (
                'id' => 99,
                'data_type_id' => 1,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            46 => 
            array (
                'id' => 100,
                'data_type_id' => 1,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            47 => 
            array (
                'id' => 101,
                'data_type_id' => 1,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            48 => 
            array (
                'id' => 102,
                'data_type_id' => 1,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 17,
            ),
            49 => 
            array (
                'id' => 103,
                'data_type_id' => 1,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            50 => 
            array (
                'id' => 104,
                'data_type_id' => 1,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            51 => 
            array (
                'id' => 131,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            52 => 
            array (
                'id' => 132,
                'data_type_id' => 11,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Especie',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            53 => 
            array (
                'id' => 133,
                'data_type_id' => 11,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Descripción / Detalle',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            54 => 
            array (
                'id' => 134,
                'data_type_id' => 11,
                'field' => 'image',
                'type' => 'text',
                'display_name' => 'Image',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            55 => 
            array (
                'id' => 135,
                'data_type_id' => 11,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 5,
            ),
            56 => 
            array (
                'id' => 136,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            57 => 
            array (
                'id' => 137,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            58 => 
            array (
                'id' => 138,
                'data_type_id' => 11,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            59 => 
            array (
                'id' => 139,
                'data_type_id' => 11,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            60 => 
            array (
                'id' => 140,
                'data_type_id' => 11,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            61 => 
            array (
                'id' => 141,
                'data_type_id' => 11,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            62 => 
            array (
                'id' => 142,
                'data_type_id' => 11,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            63 => 
            array (
                'id' => 143,
                'data_type_id' => 11,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            64 => 
            array (
                'id' => 144,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            65 => 
            array (
                'id' => 145,
                'data_type_id' => 13,
                'field' => 'icon',
                'type' => 'text',
                'display_name' => 'Icon',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            66 => 
            array (
                'id' => 146,
                'data_type_id' => 13,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Servicios',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            67 => 
            array (
                'id' => 147,
                'data_type_id' => 13,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Descripción / Detalle',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            68 => 
            array (
                'id' => 148,
                'data_type_id' => 13,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 5,
            ),
            69 => 
            array (
                'id' => 149,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            70 => 
            array (
                'id' => 150,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            71 => 
            array (
                'id' => 151,
                'data_type_id' => 13,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            72 => 
            array (
                'id' => 152,
                'data_type_id' => 13,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            73 => 
            array (
                'id' => 153,
                'data_type_id' => 13,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            74 => 
            array (
                'id' => 154,
                'data_type_id' => 13,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            75 => 
            array (
                'id' => 155,
                'data_type_id' => 13,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            76 => 
            array (
                'id' => 156,
                'data_type_id' => 13,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            77 => 
            array (
                'id' => 182,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            78 => 
            array (
                'id' => 183,
                'data_type_id' => 16,
                'field' => 'nit',
                'type' => 'text',
                'display_name' => 'NIT',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":3}}',
                'order' => 2,
            ),
            79 => 
            array (
                'id' => 184,
                'data_type_id' => 16,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":3}}',
                'order' => 3,
            ),
            80 => 
            array (
                'id' => 185,
                'data_type_id' => 16,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Telefono/Celular',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":3}}',
                'order' => 4,
            ),
            81 => 
            array (
                'id' => 186,
                'data_type_id' => 16,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":3}}',
                'order' => 5,
            ),
            82 => 
            array (
                'id' => 187,
                'data_type_id' => 16,
                'field' => 'address',
                'type' => 'text_area',
                'display_name' => 'Dirección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":12}}',
                'order' => 6,
            ),
            83 => 
            array (
                'id' => 188,
                'data_type_id' => 16,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 7,
            ),
            84 => 
            array (
                'id' => 189,
                'data_type_id' => 16,
                'field' => 'observation',
                'type' => 'text',
                'display_name' => 'Observation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            85 => 
            array (
                'id' => 190,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            86 => 
            array (
                'id' => 191,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            87 => 
            array (
                'id' => 192,
                'data_type_id' => 16,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            88 => 
            array (
                'id' => 193,
                'data_type_id' => 16,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            89 => 
            array (
                'id' => 194,
                'data_type_id' => 16,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            90 => 
            array (
                'id' => 195,
                'data_type_id' => 16,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            91 => 
            array (
                'id' => 196,
                'data_type_id' => 16,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            92 => 
            array (
                'id' => 197,
                'data_type_id' => 16,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            93 => 
            array (
                'id' => 198,
                'data_type_id' => 17,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            94 => 
            array (
                'id' => 199,
                'data_type_id' => 17,
                'field' => 'laboratory_id',
                'type' => 'text',
                'display_name' => 'Laboratory Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            95 => 
            array (
                'id' => 200,
                'data_type_id' => 17,
                'field' => 'brand_id',
                'type' => 'text',
                'display_name' => 'Brand Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            96 => 
            array (
                'id' => 201,
                'data_type_id' => 17,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagen',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":12},"resize":{"width":"1000","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 13,
            ),
            97 => 
            array (
                'id' => 203,
                'data_type_id' => 17,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Descripción / Detalle',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":12}}',
                'order' => 17,
            ),
            98 => 
            array (
                'id' => 204,
                'data_type_id' => 17,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 18,
            ),
            99 => 
            array (
                'id' => 205,
                'data_type_id' => 17,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            100 => 
            array (
                'id' => 206,
                'data_type_id' => 17,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 20,
            ),
            101 => 
            array (
                'id' => 207,
                'data_type_id' => 17,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 21,
            ),
            102 => 
            array (
                'id' => 208,
                'data_type_id' => 17,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 22,
            ),
            103 => 
            array (
                'id' => 209,
                'data_type_id' => 17,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 23,
            ),
            104 => 
            array (
                'id' => 210,
                'data_type_id' => 17,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 24,
            ),
            105 => 
            array (
                'id' => 211,
                'data_type_id' => 17,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 25,
            ),
            106 => 
            array (
                'id' => 212,
                'data_type_id' => 17,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 26,
            ),
            107 => 
            array (
                'id' => 213,
                'data_type_id' => 17,
                'field' => 'item_belongsto_laboratory_relationship',
                'type' => 'relationship',
                'display_name' => 'Laboratorio',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4},"model":"App\\\\Models\\\\Laboratory","table":"laboratories","type":"belongsTo","column":"laboratory_id","key":"id","label":"name","pivot_table":"brands","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            108 => 
            array (
                'id' => 214,
                'data_type_id' => 17,
                'field' => 'item_belongsto_brand_relationship',
                'type' => 'relationship',
                'display_name' => 'Marcas',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4},"model":"App\\\\Models\\\\Brand","table":"brands","type":"belongsTo","column":"brand_id","key":"id","label":"name","pivot_table":"brands","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            109 => 
            array (
                'id' => 217,
                'data_type_id' => 18,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            110 => 
            array (
                'id' => 218,
                'data_type_id' => 18,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Categoría',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"}}',
                'order' => 2,
            ),
            111 => 
            array (
                'id' => 219,
                'data_type_id' => 18,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Descripción / Detalle',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            112 => 
            array (
                'id' => 220,
                'data_type_id' => 18,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 4,
            ),
            113 => 
            array (
                'id' => 221,
                'data_type_id' => 18,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            114 => 
            array (
                'id' => 222,
                'data_type_id' => 18,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            115 => 
            array (
                'id' => 223,
                'data_type_id' => 18,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            116 => 
            array (
                'id' => 224,
                'data_type_id' => 18,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            117 => 
            array (
                'id' => 225,
                'data_type_id' => 18,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            118 => 
            array (
                'id' => 226,
                'data_type_id' => 18,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            119 => 
            array (
                'id' => 227,
                'data_type_id' => 18,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            120 => 
            array (
                'id' => 228,
                'data_type_id' => 18,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            121 => 
            array (
                'id' => 229,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            122 => 
            array (
                'id' => 230,
                'data_type_id' => 19,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Presentación / Unidad de Medida',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"}}',
                'order' => 2,
            ),
            123 => 
            array (
                'id' => 231,
                'data_type_id' => 19,
                'field' => 'observation',
                'type' => 'text_area',
                'display_name' => 'Observación / Descripción',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            124 => 
            array (
                'id' => 232,
                'data_type_id' => 19,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 4,
            ),
            125 => 
            array (
                'id' => 233,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Registrado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            126 => 
            array (
                'id' => 234,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            127 => 
            array (
                'id' => 235,
                'data_type_id' => 19,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            128 => 
            array (
                'id' => 236,
                'data_type_id' => 19,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            129 => 
            array (
                'id' => 237,
                'data_type_id' => 19,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            130 => 
            array (
                'id' => 238,
                'data_type_id' => 19,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            131 => 
            array (
                'id' => 239,
                'data_type_id' => 19,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            132 => 
            array (
                'id' => 240,
                'data_type_id' => 19,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            133 => 
            array (
                'id' => 242,
                'data_type_id' => 17,
                'field' => 'presentation_id',
                'type' => 'text',
                'display_name' => 'Presentation Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            134 => 
            array (
                'id' => 243,
                'data_type_id' => 17,
                'field' => 'item_belongsto_category_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Categorias',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4},"model":"App\\\\Models\\\\Category","table":"categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"brands","pivot":"0","taggable":"0"}',
                'order' => 2,
            ),
            135 => 
            array (
                'id' => 244,
                'data_type_id' => 17,
                'field' => 'category_id',
                'type' => 'text',
                'display_name' => 'Category Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            136 => 
            array (
                'id' => 245,
                'data_type_id' => 17,
                'field' => 'item_belongsto_presentation_relationship',
                'type' => 'relationship',
                'display_name' => 'Presentación',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4},"model":"App\\\\Models\\\\Presentation","table":"presentations","type":"belongsTo","column":"presentation_id","key":"id","label":"name","pivot_table":"brands","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            137 => 
            array (
                'id' => 246,
                'data_type_id' => 21,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            138 => 
            array (
                'id' => 247,
                'data_type_id' => 21,
                'field' => 'ci',
                'type' => 'text',
                'display_name' => 'Ci / Pasaporte',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191|unique:people"},"display":{"width":4}}',
                'order' => 2,
            ),
            139 => 
            array (
                'id' => 248,
                'data_type_id' => 21,
                'field' => 'first_name',
                'type' => 'text',
                'display_name' => 'Primer Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 5,
            ),
            140 => 
            array (
                'id' => 249,
                'data_type_id' => 21,
                'field' => 'middle_name',
                'type' => 'text',
            'display_name' => 'Segundo Nombre (Opcional)',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 6,
            ),
            141 => 
            array (
                'id' => 250,
                'data_type_id' => 21,
                'field' => 'paternal_surname',
                'type' => 'text',
                'display_name' => 'Apeliido Paterno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 7,
            ),
            142 => 
            array (
                'id' => 251,
                'data_type_id' => 21,
                'field' => 'maternal_surname',
                'type' => 'text',
                'display_name' => 'Apeliido Materno',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 8,
            ),
            143 => 
            array (
                'id' => 252,
                'data_type_id' => 21,
                'field' => 'birth_date',
                'type' => 'date',
                'display_name' => 'Fecha de Nacimiento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 3,
            ),
            144 => 
            array (
                'id' => 253,
                'data_type_id' => 21,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email / Correo electronico',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":4}}',
                'order' => 9,
            ),
            145 => 
            array (
                'id' => 254,
                'data_type_id' => 21,
                'field' => 'phone',
                'type' => 'number',
                'display_name' => 'Telefono / Celular',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":2}}',
                'order' => 11,
            ),
            146 => 
            array (
                'id' => 255,
                'data_type_id' => 21,
                'field' => 'address',
                'type' => 'text_area',
                'display_name' => 'Dirección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:191"},"display":{"width":12}}',
                'order' => 14,
            ),
            147 => 
            array (
                'id' => 256,
                'data_type_id' => 21,
                'field' => 'gender',
                'type' => 'select_dropdown',
                'display_name' => 'Género',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"options":{"Masculino":"Masculino","Femenino":"Femenino"},"display":{"width":4},"validation":{"rule":"required"}}',
                'order' => 4,
            ),
            148 => 
            array (
                'id' => 257,
                'data_type_id' => 21,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Fotografía',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":9},"resize":{"width":"1000","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 13,
            ),
            149 => 
            array (
                'id' => 258,
                'data_type_id' => 21,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Activo","off":"Inactivo","checked":true}',
                'order' => 15,
            ),
            150 => 
            array (
                'id' => 259,
                'data_type_id' => 21,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            151 => 
            array (
                'id' => 260,
                'data_type_id' => 21,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 17,
            ),
            152 => 
            array (
                'id' => 261,
                'data_type_id' => 21,
                'field' => 'registerUser_id',
                'type' => 'text',
                'display_name' => 'RegisterUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            153 => 
            array (
                'id' => 262,
                'data_type_id' => 21,
                'field' => 'registerRole',
                'type' => 'text',
                'display_name' => 'RegisterRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            154 => 
            array (
                'id' => 263,
                'data_type_id' => 21,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 20,
            ),
            155 => 
            array (
                'id' => 264,
                'data_type_id' => 21,
                'field' => 'deleteUser_id',
                'type' => 'text',
                'display_name' => 'DeleteUser Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 21,
            ),
            156 => 
            array (
                'id' => 265,
                'data_type_id' => 21,
                'field' => 'deleteRole',
                'type' => 'text',
                'display_name' => 'DeleteRole',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 22,
            ),
            157 => 
            array (
                'id' => 266,
                'data_type_id' => 21,
                'field' => 'deleteObservation',
                'type' => 'text',
                'display_name' => 'DeleteObservation',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 23,
            ),
            158 => 
            array (
                'id' => 267,
                'data_type_id' => 17,
                'field' => 'fraction',
                'type' => 'checkbox',
                'display_name' => 'Venta por Fracción',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"on":"Si","off":"No","checked":false}',
                'order' => 14,
            ),
            159 => 
            array (
                'id' => 268,
                'data_type_id' => 17,
                'field' => 'fractionPresentation_id',
                'type' => 'text',
                'display_name' => 'FractionPresentation Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            160 => 
            array (
                'id' => 269,
                'data_type_id' => 17,
                'field' => 'fractionQuantity',
                'type' => 'number',
                'display_name' => 'Cantidad Fraccionada',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":3}}',
                'order' => 15,
            ),
            161 => 
            array (
                'id' => 270,
                'data_type_id' => 17,
                'field' => 'item_belongsto_presentation_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Presentacion Fraccionaria',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":3},"model":"App\\\\Models\\\\Presentation","table":"presentations","type":"belongsTo","column":"fractionPresentation_id","key":"id","label":"name","pivot_table":"brands","pivot":"0","taggable":"0"}',
                'order' => 16,
            ),
            162 => 
            array (
                'id' => 271,
                'data_type_id' => 8,
                'field' => 'country_code',
                'type' => 'country_code',
                'display_name' => 'Código',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":2}}',
                'order' => 10,
            ),
            163 => 
            array (
                'id' => 272,
                'data_type_id' => 21,
                'field' => 'country_code',
                'type' => 'country_code',
                'display_name' => 'Código',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"display":{"width":2}}',
                'order' => 10,
            ),
            164 => 
            array (
                'id' => 273,
                'data_type_id' => 21,
                'field' => 'porcentage_commission',
                'type' => 'number',
                'display_name' => 'Porcentage de Comisión',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":3}}',
                'order' => 12,
            ),
            165 => 
            array (
                'id' => 274,
                'data_type_id' => 17,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|max:191"},"display":{"width":4}}',
                'order' => 7,
            ),
        ));
        
        
    }
}