<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('items')->delete();
        
        \DB::table('items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Comederos perros',
                'nameTrade' => 'Comederos perros',
                'observation' => 'platos de aluminio grande',
                'status' => 1,
                'created_at' => '2025-12-04 07:24:41',
                'updated_at' => '2025-12-04 07:24:41',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Comederos gatos',
                'nameTrade' => 'Comederos gatos',
                'observation' => 'patos de plastico',
                'status' => 1,
                'created_at' => '2025-12-04 07:25:21',
                'updated_at' => '2025-12-04 07:25:21',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collarin',
                'nameTrade' => 'Collarin',
                'observation' => 'Collarin isabelina p',
                'status' => 1,
                'created_at' => '2025-12-04 07:26:01',
                'updated_at' => '2025-12-04 07:26:01',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collarin',
                'nameTrade' => 'Collarin',
                'observation' => 'Collarin isabelina m',
                'status' => 1,
                'created_at' => '2025-12-04 07:26:27',
                'updated_at' => '2025-12-04 07:26:27',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collarin',
                'nameTrade' => 'Collarin',
                'observation' => 'Collarin isabelina G',
                'status' => 1,
                'created_at' => '2025-12-04 07:27:04',
                'updated_at' => '2025-12-04 07:27:04',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collarin',
                'nameTrade' => 'Collarin',
                'observation' => 'Collarin isabelina GG',
                'status' => 1,
                'created_at' => '2025-12-04 07:27:25',
                'updated_at' => '2025-12-04 07:27:25',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Corta uña',
                'nameTrade' => 'Corta uña',
                'observation' => 'Corta uña canino',
                'status' => 1,
                'created_at' => '2025-12-04 07:27:47',
                'updated_at' => '2025-12-04 07:27:47',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Furmineitor',
                'nameTrade' => 'Furmineitor',
                'observation' => 'peineta',
                'status' => 1,
                'created_at' => '2025-12-04 07:28:07',
                'updated_at' => '2025-12-04 07:28:07',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Peines',
                'nameTrade' => 'Peines',
                'observation' => 'peines plastico',
                'status' => 1,
                'created_at' => '2025-12-04 07:28:30',
                'updated_at' => '2025-12-04 07:28:30',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Peines',
                'nameTrade' => 'Peines',
                'observation' => 'peines gatos',
                'status' => 1,
                'created_at' => '2025-12-04 07:28:54',
                'updated_at' => '2025-12-04 07:28:54',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Deslanadores',
                'nameTrade' => 'Deslanadores',
                'observation' => 'Deslanadores caninos',
                'status' => 1,
                'created_at' => '2025-12-04 07:29:11',
                'updated_at' => '2025-12-04 07:29:11',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Peines dobles',
                'nameTrade' => 'Peines dobles',
                'observation' => 'peines doble cara',
                'status' => 1,
                'created_at' => '2025-12-04 07:29:32',
                'updated_at' => '2025-12-04 07:29:32',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Cadenas largas',
                'nameTrade' => 'Cadenas largas',
                'observation' => 'cadenas de metal',
                'status' => 1,
                'created_at' => '2025-12-04 07:29:51',
                'updated_at' => '2025-12-04 07:29:51',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Cadena denucia',
                'nameTrade' => 'Cadena denucia',
                'observation' => 'collar de ahorque 1',
                'status' => 1,
                'created_at' => '2025-12-04 07:30:06',
                'updated_at' => '2025-12-04 07:30:06',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Cadena denucia',
                'nameTrade' => 'Cadena denucia',
                'observation' => 'collar de ahorque 2',
                'status' => 1,
                'created_at' => '2025-12-04 07:30:24',
                'updated_at' => '2025-12-04 07:30:24',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Cadena denucia',
                'nameTrade' => 'Cadena denucia',
                'observation' => 'collar de ahorque 3',
                'status' => 1,
                'created_at' => '2025-12-04 07:31:06',
                'updated_at' => '2025-12-04 07:31:06',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Cadena Chain',
                'nameTrade' => 'Cadena Chain',
                'observation' => 'Collar de ahorque 4',
                'status' => 1,
                'created_at' => '2025-12-04 07:31:21',
                'updated_at' => '2025-12-04 07:31:21',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collares',
                'nameTrade' => 'Collares',
                'observation' => 'collares con cascabel',
                'status' => 1,
                'created_at' => '2025-12-04 07:31:35',
                'updated_at' => '2025-12-04 07:31:35',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Cama de gato',
                'nameTrade' => 'Cama de gato',
                'observation' => 'Iglu cama',
                'status' => 1,
                'created_at' => '2025-12-04 07:31:51',
                'updated_at' => '2025-12-04 07:31:51',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collar amarillo',
                'nameTrade' => 'Collar amarillo',
                'observation' => 'collar de cuero amarillo',
                'status' => 1,
                'created_at' => '2025-12-04 07:32:35',
                'updated_at' => '2025-12-04 07:32:35',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collar verde',
                'nameTrade' => 'Collar verde',
                'observation' => 'collar de cuero verde',
                'status' => 1,
                'created_at' => '2025-12-04 07:32:48',
                'updated_at' => '2025-12-04 07:32:48',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collar azul',
                'nameTrade' => 'Collar azul',
                'observation' => 'collar de cuero azul',
                'status' => 1,
                'created_at' => '2025-12-04 07:33:02',
                'updated_at' => '2025-12-04 07:33:02',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collares de cuerina',
                'nameTrade' => 'Collares de cuerina',
                'observation' => 'collares pequeño de cuerina',
                'status' => 1,
                'created_at' => '2025-12-04 07:33:22',
                'updated_at' => '2025-12-04 07:33:22',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Collare de cuero',
                'nameTrade' => 'Collare de cuero',
                'observation' => 'collares de cuero pequeño',
                'status' => 1,
                'created_at' => '2025-12-04 07:33:37',
                'updated_at' => '2025-12-04 07:33:37',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Pecheras',
                'nameTrade' => 'Pecheras',
                'observation' => 'pecheras verde azul',
                'status' => 1,
                'created_at' => '2025-12-04 07:33:52',
                'updated_at' => '2025-12-04 07:33:52',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Pecheras',
                'nameTrade' => 'Pecheras',
                'observation' => 'pechera morada',
                'status' => 1,
                'created_at' => '2025-12-04 07:34:09',
                'updated_at' => '2025-12-04 07:34:09',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Masco pets',
                'nameTrade' => 'Masco pets',
                'observation' => 'collar mas correa',
                'status' => 1,
                'created_at' => '2025-12-04 07:34:31',
                'updated_at' => '2025-12-04 07:34:31',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Masco pets',
                'nameTrade' => 'Masco pets',
                'observation' => 'pechera mas correa',
                'status' => 1,
                'created_at' => '2025-12-04 07:34:45',
                'updated_at' => '2025-12-04 07:34:45',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Vestidos',
                'nameTrade' => 'Vestidos',
                'observation' => 'vestido hembra',
                'status' => 1,
                'created_at' => '2025-12-04 07:35:18',
                'updated_at' => '2025-12-04 07:35:18',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Camisas',
                'nameTrade' => 'Camisas',
                'observation' => 'camisa macho',
                'status' => 1,
                'created_at' => '2025-12-04 07:35:28',
                'updated_at' => '2025-12-04 07:38:06',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Palas',
                'nameTrade' => 'Palas',
                'observation' => 'palas de plastico',
                'status' => 1,
                'created_at' => '2025-12-04 07:42:56',
                'updated_at' => '2025-12-04 07:42:56',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Guantes',
                'nameTrade' => 'Guantes',
                'observation' => 'guantes de peinado',
                'status' => 1,
                'created_at' => '2025-12-04 07:43:09',
                'updated_at' => '2025-12-04 07:43:09',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Bolso',
                'nameTrade' => 'Bolso',
                'observation' => 'bolson grande',
                'status' => 1,
                'created_at' => '2025-12-04 07:43:24',
                'updated_at' => '2025-12-04 07:43:24',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Bolso',
                'nameTrade' => 'Bolso',
                'observation' => 'bolso mediano',
                'status' => 1,
                'created_at' => '2025-12-04 07:43:43',
                'updated_at' => '2025-12-04 07:43:43',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Bolso',
                'nameTrade' => 'Bolso',
                'observation' => 'bolso pequeño',
                'status' => 1,
                'created_at' => '2025-12-04 07:44:07',
                'updated_at' => '2025-12-04 07:44:07',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Pechera',
                'nameTrade' => 'Pechera',
                'observation' => 'pechera militar pza',
                'status' => 1,
                'created_at' => '2025-12-04 07:44:25',
                'updated_at' => '2025-12-04 07:44:25',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Bozal',
                'nameTrade' => 'Bozal',
                'observation' => 'bozal para perros m',
                'status' => 1,
                'created_at' => '2025-12-04 07:44:43',
                'updated_at' => '2025-12-04 07:44:43',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Bozal',
                'nameTrade' => 'Bozal',
                'observation' => 'bozal para perros g',
                'status' => 1,
                'created_at' => '2025-12-04 07:45:01',
                'updated_at' => '2025-12-04 07:45:01',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'category_id' => 2,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Aminort',
                'nameTrade' => 'Aminort',
                'observation' => 'aminort 50 ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:45:42',
                'updated_at' => '2025-12-04 07:45:42',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'category_id' => 2,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Aminort',
                'nameTrade' => 'Aminort',
                'observation' => 'aminort 30 ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:46:23',
                'updated_at' => '2025-12-04 07:46:23',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'category_id' => 1,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Aminort',
                'nameTrade' => 'Aminort',
                'observation' => 'aminort 15ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:46:44',
                'updated_at' => '2025-12-04 07:46:44',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'category_id' => 3,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Levofarma',
                'nameTrade' => 'Levofarma',
                'observation' => 'levofarma 15ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:47:55',
                'updated_at' => '2025-12-04 07:47:55',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'category_id' => 3,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Biomisol',
                'nameTrade' => 'Biomisol',
                'observation' => 'biomisol 15 ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:48:09',
                'updated_at' => '2025-12-04 07:48:21',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'category_id' => 4,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Talco sanitario',
                'nameTrade' => 'Talco sanitario',
                'observation' => 'Talco 60 gr',
                'status' => 1,
                'created_at' => '2025-12-04 07:48:47',
                'updated_at' => '2025-12-04 07:48:47',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'category_id' => 5,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Bioderm',
                'nameTrade' => 'Bioderm',
                'observation' => 'Jabon 90 gr',
                'status' => 1,
                'created_at' => '2025-12-04 07:49:12',
                'updated_at' => '2025-12-04 07:49:12',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'category_id' => 6,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Lidocaina',
                'nameTrade' => 'Lidocaina',
                'observation' => 'Lidocaina 2 %',
                'status' => 1,
                'created_at' => '2025-12-04 07:50:43',
                'updated_at' => '2025-12-04 07:50:43',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'category_id' => 7,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Desalgina',
                'nameTrade' => 'Desalgina',
                'observation' => 'Desalgina 100ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:51:05',
                'updated_at' => '2025-12-04 07:51:05',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'category_id' => 7,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Ketoprefeno',
                'nameTrade' => 'Ketoprefeno',
                'observation' => 'Ketoprofeno 50ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:51:27',
                'updated_at' => '2025-12-04 07:51:27',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'category_id' => 8,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Oxisan plus',
                'nameTrade' => 'Oxisan plus',
                'observation' => 'Oxisan 50ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:51:57',
                'updated_at' => '2025-12-04 07:51:57',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'category_id' => 9,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Xylasina 2%',
                'nameTrade' => 'Xylasina 2%',
                'observation' => 'Xylasina 30 ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:52:30',
                'updated_at' => '2025-12-04 07:52:30',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'category_id' => 9,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Ketamina 10%',
                'nameTrade' => 'Ketamina 10%',
                'observation' => 'Ketamina 10 ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:53:05',
                'updated_at' => '2025-12-04 07:53:05',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'category_id' => 10,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Fenestrol',
                'nameTrade' => 'Fenestrol',
                'observation' => 'Fenestrol 5ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:53:34',
                'updated_at' => '2025-12-04 07:53:34',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'category_id' => 11,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Petbrilho',
                'nameTrade' => 'Petbrilho',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-12-04 07:54:54',
                'updated_at' => '2025-12-04 07:54:54',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'category_id' => 11,
                'presentation_id' => 2,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Coco petbrilho',
                'nameTrade' => 'Coco petbrilho',
                'observation' => 'Shampoo 500 ml',
                'status' => 1,
                'created_at' => '2025-12-04 07:55:13',
                'updated_at' => '2025-12-04 07:55:22',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'category_id' => 12,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'CPV Parvovirus',
                'nameTrade' => 'CPV Parvovirus',
                'observation' => 'Casete',
                'status' => 1,
                'created_at' => '2025-12-04 07:55:49',
                'updated_at' => '2025-12-04 07:55:49',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'category_id' => 13,
                'presentation_id' => 1,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'CDV Moquillo',
                'nameTrade' => 'CDV Moquillo',
                'observation' => 'Casete',
                'status' => 1,
                'created_at' => '2025-12-04 07:56:11',
                'updated_at' => '2025-12-04 07:56:11',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'category_id' => 14,
                'presentation_id' => 3,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Alimento Balanceado adulto',
                'nameTrade' => 'Alimento Balanceado adulto',
                'observation' => 'Dogstar 20kg',
                'status' => 1,
                'created_at' => '2025-12-04 07:56:41',
                'updated_at' => '2025-12-04 07:57:24',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'category_id' => 14,
                'presentation_id' => 3,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Alimento balanceado cachorro',
                'nameTrade' => 'Alimento balanceado cachorro',
                'observation' => 'Dogstar 20kg',
                'status' => 1,
                'created_at' => '2025-12-04 07:57:06',
                'updated_at' => '2025-12-04 07:57:06',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'category_id' => 14,
                'presentation_id' => 3,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Alimento balanceado adulto carne',
                'nameTrade' => 'Alimento balanceado adulto carne',
                'observation' => 'Mican 20kg',
                'status' => 1,
                'created_at' => '2025-12-04 07:57:45',
                'updated_at' => '2025-12-04 07:57:45',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'category_id' => 14,
                'presentation_id' => 3,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Alimento Balanceado Cachorro',
                'nameTrade' => 'Alimento Balanceado Cachorro',
                'observation' => 'Mican 20kg',
                'status' => 1,
                'created_at' => '2025-12-04 07:58:10',
                'updated_at' => '2025-12-04 07:58:10',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'category_id' => 14,
                'presentation_id' => 3,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Alimento Balanceado Gatos',
                'nameTrade' => 'Alimento Balanceado Gatos',
                'observation' => 'Felino 20kg',
                'status' => 1,
                'created_at' => '2025-12-04 07:59:00',
                'updated_at' => '2025-12-04 07:59:00',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'category_id' => 14,
                'presentation_id' => 3,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Alimento balanceado adulto pollo',
                'nameTrade' => 'Alimento balanceado adulto pollo',
                'observation' => 'Mican 20kg',
                'status' => 1,
                'created_at' => '2025-12-04 07:59:18',
                'updated_at' => '2025-12-04 07:59:18',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'category_id' => 14,
                'presentation_id' => 3,
                'laboratory_id' => NULL,
                'brand_id' => NULL,
                'image' => NULL,
                'nameGeneric' => 'Alimento Balanceado Adulto',
                'nameTrade' => 'Alimento Balanceado Adulto',
                'observation' => 'Dogstar 20kg',
                'status' => 1,
                'created_at' => '2025-12-04 07:59:40',
                'updated_at' => '2025-12-04 07:59:40',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
        ));
        
        
    }
}