<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-house',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:31:13',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:40:50',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:33:38',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:33:29',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:33:17',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:40:50',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:40:50',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2024-10-17 16:40:50',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2024-10-17 14:28:27',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2024-10-17 16:33:05',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2024-12-08 12:33:25',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Administración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-regular fa-folder-open',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2025-02-09 15:42:49',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Clientes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 3,
                'created_at' => '2025-04-06 09:43:00',
                'updated_at' => '2025-12-07 11:24:39',
                'route' => 'voyager.people.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Parámetro de Inventario',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2025-12-01 09:46:20',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Compras / Ingresos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-plus',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2025-12-01 10:39:56',
                'updated_at' => '2025-12-06 04:47:20',
                'route' => 'incomes.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Proveedores',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ship',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 3,
                'created_at' => '2025-12-01 10:51:18',
                'updated_at' => '2025-12-03 15:02:16',
                'route' => 'voyager.suppliers.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Productos / Items',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-shopping',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2025-12-01 11:13:15',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => 'voyager.items.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Categorías',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-layer-group',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 1,
                'created_at' => '2025-12-03 14:57:21',
                'updated_at' => '2025-12-03 15:02:08',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Presentaciones / Unidad Medidas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ticket',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 2,
                'created_at' => '2025-12-03 15:01:29',
                'updated_at' => '2025-12-03 15:02:16',
                'route' => 'voyager.presentations.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Cajas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cash-register',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2025-12-10 03:26:08',
                'updated_at' => '2025-12-10 03:34:55',
                'route' => 'cashiers.index',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-plus',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2025-12-10 03:35:18',
                'updated_at' => '2025-12-10 03:37:46',
                'route' => 'sales.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}